### ISSUE TITLE
Problemes amb els fotogrames.

### ISSUE THREAD

**Issue by IgnaFiz** [OpenICGC/QgisPlugin#13]
Bon día,

Estic fent servir el complement i tincs problemes per carregar els fotogrames del ICGC. Al seleccionar un fotograma i al fer la funció Visualizar no apareix el fotograma, ni tampoc apareix la funció Información.

Tinc la versio. 3.28 de QGIS i Windows 11 i la darrera versió del component.

Salut
Ignacio

**Comment by icgcaadell** [comment]
Hola,

Estic fent proves avui amb un QGIS 3.28.1 a Win10 i sembla que tot funciona correctament (he cercat fotogrames en un punt aleatori i he consultat informació i mostrat el raster d'ells).
Persisteix el problema avui? Et dóna algun tipus d'error QGIS?
Si segueixes tenint el problema, podries activar el "registre d'informació de depuració" (menú\ajuda\depuració\activar registre...) i enviar-nos la informació que et mostri? (crearà una pestanya al registre de missatges de QGIS anomenada OpenICGC i allà anirà mostrant informació diversa)

Gràcies!

**Comment by IgnaFiz** [comment]
Bon día,

He fet proves i no em funciona tampoc, no visualitzo informació ni el fotograma.  Us faig a mans el document de depuració.
[OpenICGC.log](https://github.com/OpenICGC/QgisPlugin/files/11097915/OpenICGC.log)


Gràcies!

**Comment by icgcaadell** [comment]
Hola

Gràcies per la informació. Quan dius que no visualitzes informació ni el fotograma, vols dir que et carrega la llista de fotogrames i que quan en selecciones un no et deixa mostrar ni informació ni raster? però si que et carrega la llista? En el log veig que et dóna unes alertes carregant un polígon de límits de Catalunya que fem servir per descartar cerques fora de zona...

Estaries en aquesta situació però sense que facin res els botons d'info i visualització?
![image](https://user-images.githubusercontent.com/47522822/228488733-01b46dea-4875-4256-95bf-db0ea32e3675.png)

**Comment by IgnaFiz** [comment]
Efectivament, aquesta es la situació. Apareix la llista de fotogrames (finestra de la dreta), puc veure la llista segons anys amb el selector i es despliega la capa de fotogrames  de la esquerra. Pero al seleccionar un fotograma i premer el botó de visualitzar o d'informació no apareix cap dels dos. 

Vaig provar amb la versió de QGIS 3.22.13 per si era un problema de versió, pero apareix els mateix problema.

Gracies!

**Comment by icgcaadell** [comment]
Crec que has tancat la incidència per error, la reobro

**Comment by IgnaFiz** [comment]
Ostres si...gràcies!

**Comment by jarnaldich** [comment]
Bon dia, no aconseguim reproduir la incidència, si vols podem concertar una reunió per Teams per tal de mirar-nos-ho plegats. En cas que sigui així, si us plau envia'ns un correu indicant disponibilitat a qgis.openicgc@icgc.cat per evitar publicar l'enllaç de reunió aqui. Gràcies!

**Comment by icgcaadell** [comment]
Finalment hem aconseguit reproduir la incidència, el problema era degut a un error del plugin al fer cerques de fotogrames mitjançant una consulta via arxius geojson després de modificar la configuració "locale" de python

Si s'executa aquest codi tenint Windows amb configuració regional en Català (o diferent d'anglès):
`import locale`
`locale.setlocale(locale.LC_ALL, '')`
i després es carrega un arxiu geojson, la detecció d'elements seleccionats dins el geojson deixa de funcionar...
He reprogramat una part del codi eliminant aquestes línies i sembla que s'ha solucionat el problema.

Hem obert incidència a QGIS per si volen tenir en consideració aquest problema:
[https://github.com/qgis/QGIS/issues/52731]

En qualsevol cas tot hauria de tornar a funcionar a partir de la versió de plugin v1.1.13 disponible des de la botiga de QGIS.
Gràcies per l'ajuda!

**Comment by icgcaadell** [comment]
Sembla que no està donant problemes la versió 1.1.13 així que dono per tancada la incidència.
Gràcies!

**Comment by IgnaFiz** [comment]
Si, va perfecte.

Moltes gràcies!!

Ignacio Fiz

Prof. Agregado Serra Hunter / Investigador (R4) de l'Institut Català d'Arqueologia Clàssica (ICAC)

Departamento de Historia e Historia del Arte

Universidad Rovira i Virgili (URV)

Av Catalunya 35.

43003 Tarragona  (Campus Catalunya)

Orcid: https://orcid.org/0000-0003-2503-9078
Latest publication: https://www.youtube.com/watch?v=3pCMOoCIIPA
https://www.mdpi.com/2504-446X/6/3/59/htm
                                     https://www.mdpi.com/2072-4292/13/12/2344

https://www.researchgate.net/profile/Jose_Fiz_Fernandez2

https://icac.academia.edu/IgnacioFiz

________________________________
De: icgcaadell ***@***.***>
Enviat el: dimarts, 2 de maig de 2023 7:51
Per a: OpenICGC/QgisPlugin ***@***.***>
A/c: José Ignacio Fiz Fernández ***@***.***>; State change ***@***.***>
Tema: Re: [OpenICGC/QgisPlugin] Problemes amb els fotogrames. (Issue #13)


Sembla que no està donant problemes la versió 1.1.13 així que dono per tancada la incidència.
Gràcies!
