### ISSUE TITLE
Error al iniciar QGIS, no carrega el complement OpenICGC

### ISSUE THREAD

**Issue by sammy-iatta** [OpenICGC/QgisPlugin#16]
Bon dia.
El complement no es carrega correctament (només algunes vegades) al iniciar el QGIS.
Dona un error de timeout, i pel recorregut de l'error sembla que és intentant recollir la informació de les ortos històriques.

Degut a l'error el complement queda inhabilitat i no es mostra a QGIS.
Per si el voleu tenir en compte, l'error només ens passa a la oficina, segurament hi ha algun problema en la nostre connexió, i tampoc ens passa sempre.

Crec que seria interessant que el complement no quedés amagat en cas de no poder carregar alguna sèrie.

Passo bolcat de pantalla amb l'error:
![image](https://github.com/OpenICGC/QgisPlugin/assets/74067470/cc4df2ec-733b-4e14-9069-9a1055653de5)

Moltes gracies

**Comment by icgcaadell** [comment]
Hola

Gràcies per reportar la incidència. 

Tens raó, a l'arrencar el plugin es busquen recursos disponibles en els servidors de l'ICGC i es generen el menús de productes a partir d'aquestes consultes. He revisat el codi i veig que tenia protegida la connexió amb els servidor (open) però no la lectura posterior de dades (read), això provoca l'error i fa que no s'inicialitzin correctament els menús.

Modifico el codi i publico una nova versió del plugin en breu.

Salutacions!

**Comment by icgcaadell** [comment]
Hola

Avui he publicat la versió v1.1.17 del connector que protegeix la lectura de recursos i hauria d'evitar l'error que comentaves. En qualsevol cas, si falla l'accés a algun recurs aquest no apareixerà com a disponible en els menús del plugin.

Podries actualitzar-te el connector i veure si s'ha solucionat el problema?

Salutacions

**Comment by sammy-iatta** [comment]
Bon dia.

Disculpeu, que jo vaig obrir el tema i em vaig desconnectar per Setmana Santa sense proposar solucions ni aportar res.

Complement instal·lat i funcionant, moltes gracies

**Comment by icgcaadell** [comment]
Bon dia

Cap problema, m'espero uns dies per veure si dóna algun problema i si no hi ha novetats tanco la incidència

Salutacions

**Comment by icgcaadell** [comment]
Tanco la incidència
