### ISSUE TITLE
GSD erroni?

### ISSUE THREAD

**Issue by Isaac0H0E** [OpenICGC/QgisPlugin#19]
Hola, El GSD de les imatges aèries de les fitxes de les imatges en general no coincideix amb el GSD que doneu a la graella de fotogrames . (veure captura de pantalla adjunta) 
![Captura de pantalla 2024-08-19 165931](https://github.com/user-attachments/assets/5a52ae58-6008-4c79-a1c1-0a2c59806e91)

**Comment by icgcaadell** [comment]
Bon dia

Disculpa per trigar en contestar, aquests dies estàvem de vacances.

Tens raó alguna cosa està passant amb la selecció dels elements, fixat que el nom de fitxer no coincideix amb el que tens seleccionat i entenc que per això et surt el GSD malament (i la resta de metadades suposo que també)
Estem fent canvis en el servidor que publica les dades que visualitza OpenICGC i deu haver algun efecte no desitjat.

Ho investiguem, gràcies per reportar l'error

**Comment by Isaac-h-e** [comment]
Bon dia!

No passa res, espero que les vacances hagin estat profitoses.

Si, lo del nom de la imatge em va estranyar però no ho vaig veure fins després de crear aquesta incidència així que al final no vaig dir res... A veure si aquests canvis en els servidors permetran la descarrega integra de fotogrames ;-) 

Gràcies a vosaltres per la gran tasca que feu!

Isaac

**Comment by icgcaadell** [comment]
Hola

Ja he trobat el problema, està relacionat amb els identificadors de fotogrames que guarda QGIS a la seva capa i obté del servei WFS de l'Institut. Ja ho tinc corregit i farem una publicació per arreglar-ho.

Sobre la descàrrega de fotogrames, inicialment es va descartar degut a que fotogrames de molta resolució poden ser relativament "pesats" i ocupar uns centenar de MB que podrien saturar els nostres servidors de descàrrega. Ara com hauràs vist està limitat a àrees amb certa quantitat de píxels. A nivell de plugin no costaria de fer. En qualsevol cas comentaré la petició a veure si seria viable.

Deixo la incidència oberta fins que pugui publicar l'actualització

Salutacions

**Comment by Isaac-h-e** [comment]
Hola!

Gràcies per l'actualització! 

Salutacions

**Comment by Isaac-h-e** [comment]
Hola Albert,

Acabo de tornar intentar baixar-me fotogrames de l'àrea de Barcelona i crec que segueixo observant el mateix problema per tant diria que no està arranjat, em podries donar una estimació aproximada de quan podré baixar fotogrames amb el connector del QGIS?

Gracies!

Isaac

**Comment by icgcaadell** [comment]
Hola

No, no, encara no he publicat la versió que corregeix el problema (serà la 1.1.20), estic arreglant un altra incidència que m'han reportat per email relacionada amb anàglif i espero publicar la nova versió avui o demà a primera hora.

Disculpa l'endarreriment!

**Comment by Isaac-h-e** [comment]
Hola Albert,

Moltes gràcies, cap problema!

Salut!

**Comment by icgcaadell** [comment]
Bon dia

Estic tenint problemes per publicar la v1.1.20 del plugin al repositori de QGIS.
Pots provar de descarregar-lo directament de github i instal·lar-lo des de Zip, a veure si et soluciona el problema?

https://github.com/OpenICGC/QgisPlugin/releases

Gràcies!

**Comment by icgcaadell** [comment]
Finalment ja he pogut publicar al repositori de QGIS (han canviat l'estructura de fitxers que accepten), també et pots descarregar la versió v1.1.20 directament des de QGIS!

**Comment by Isaac-h-e** [comment]
Genial! moltes gràcies i molt agraït Albert!

Pel que fa a la possibilitat de descarregar fotogrames integres, el motiu de la meva sol·licitud es que l'IGN permet la descàrrega de fotogrames integres però per desgràcia l'IGN no disposa dels vols a 8cm que disposa l'ICGC...

En fi, s'ha intentat...

Isaac

**Comment by icgcaadell** [comment]
De res, per això estem.

Respecte a la descàrrega de fotogrames, ho comentaré al meu cap i farem quatre números a veure si els servidors ho suportarien... no desesperis!

Si em confirmes que et funciona correctament la v1.1.20 tanco la incidència

**Comment by Isaac-h-e** [comment]
Hola Albert,

Bon dia, confirmo que la nova versió v1.1.20 funciona adequadament!

Salut

Isaac

**Comment by icgcaadell** [comment]
Bon dia

Perfecte! Tanco la incidència.
Si tornes a detectar qualsevol error reobre la incidència o crea nova, cap problema

Salutacions!

**Comment by icgcaadell** [comment]
Hola un altre cop Isaac

Referent a la possibilitat de descarregar fotogrames sencers, hem estat fent unes quantes estimacions i en la propera versió 1.1.22 (espero publicar-la la setmana vinent) estarà disponible aquesta opció:

![image](https://github.com/user-attachments/assets/a521b5aa-29ec-4ea6-b873-50d8f9808315)

Caldrà seleccionar el tipus de descàrrega "Dades disponibles" (per fer-ho similar a descàrregues d'altres tipus de productes). Esperem que et sigui d'utilitat. Salutacions

Albert

**Comment by Isaac-h-e** [comment]
Hola Albert,
Molt bon dia! (assumeixo que llegiras el correu el dilluns pel matí) Ostres! quina sorpresa! No m'ho esperava pas, moltes gràcies per haver tingut en compte la meva petició.
Ja et dic que en seré un bon tester perque tinc uns quants projectes fotogrmètrics pendents, especialment en entorns urbans, vaja que descarregaré força imatges.
Gràcies també per haver'm-ho fet saber i a la resta de l'equip!
Salutacions
Isaac Hoyas Ester    On Friday 11 October 2024 at 09:14:21 CEST, Albert ***@***.***> wrote:  
 
 


Hola un altre cop Isaac

Referent a la possibilitat de descarregar fotogrames sencers, hem estat fent unes quantes estimacions i en la propera versió 1.1.22 (espero publicar-la la setmana vinent) estarà disponible aquesta opció:

image.png (view on web)

Caldrà seleccionar el tipus de descàrrega "Dades disponibles" (per fer-ho similar a descàrregues d'altres tipus de productes). Esperem que et sigui d'utilitat. Salutacions

Albert

**Comment by icgcaadell** [comment]
Bon dia

Versió 1.1.22 publicada! De res, gràcies per reportar qualsevol problema i ajudar a arreglar-lo.
Tots els comentaris son benvingut, al mateix plugin hi ha una opció al menú d'ajudar per enviar-ne.
Salutacions

Albert
