### ISSUE TITLE
Error en clicar en elements de la taula de continguts

### ISSUE THREAD

**Issue by ValentinSastre** [OpenICGC/QgisPlugin#5]
En la versió de QGIS 3.16.6-Hannover, amb el plugin Open ICGC instal·lat, salta el següent error de Python cada vegada que es fa clic en un element de la taula de continguts:

```
S'ha produït un error mentre executava codi python: 

AttributeError: 'NoneType' object has no attribute 'setEnabled' 
Traceback (most recent call last):
  File "C:/Users/v.sastre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\openicgc.py", line 673, in on_click_legend
    product_submenu = []
AttributeError: 'NoneType' object has no attribute 'setEnabled'


Versió phyton: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versió del QGIS: 3.16.6-Hannover Hannover, bfd36fddc9 

Ruta del Python:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/v.sastre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/v.sastre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/v.sastre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\v.sastre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:/Users/v.sastre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib
C:/Users/v.sastre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib
C:/Users/v.sastre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib
```

Reinstal·lant el connector (esborrant també manualment la carpeta del plugin) i tornant a instal·lar-lo el problema persisteix.

**Comment by icgcaadell** [comment]
Hola, gràcies per reportar l'error. Només he aconseguit reproduir-lo en un entorn Linux/Ubuntu, és correcte? En quin sistema operatiu estàs executant el plugin de QGIS?

Sembla que hi ha un problema en l'event que activa els botons d'estil i sèries temporals...

**Comment by ValentinSastre** [comment]
Hola, gràcies per la ràpida resposta. 

El sistema operatiu és Windows 10.
![image](https://user-images.githubusercontent.com/61157505/149782517-0dfc8356-9566-48d4-9797-48241d67c532.png)

**Comment by icgcaadell** [comment]
No aconsegueixo reproduir l'error en Windows però l'he pogut arreglar en Linux. Podries provar si la correcció també funciona en el teu cas? De moment només l'he publicat a github:

https://github.com/OpenICGC/QgisPlugin/releases/download/v1.0.7/OpenICGC-1.0.7.zip

Pots instal·lar-lo via zip i em confirmes si et funciona bé o no? Si tot va bé actualitzo la botiga de QGIS. Gràcies

**Comment by ValentinSastre** [comment]
L'he instal·lat via ZIP i efectivament l'error ja s'ha solucionat i funciona correctament. Moltes gràcies!

**Comment by icgcaadell** [comment]
Perfecte, de res! He actualitzat el connector també a la botiga de QGIS.
Tanco la incidència.
