### ISSUE TITLE
Amb l'anterior versió de la barra "OpenICGC" la descarrega de fotogrames funcionava però amb versió 1.1.5 no funciona.

### ISSUE THREAD

**Issue by Isaac0H0E** [OpenICGC/QgisPlugin#6]
`2022-05-24T10:40:34     WARNING    Map request failed [error: Error transferring https://fototeca-connector.icgc.cat/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=433987.6893147789524,4599402.361215376295,437186.4004343083943,4601011.033409469761&CRS=EPSG:25831&WIDTH=1030&HEIGHT=518&LAYERS=fotos&STYLES=2011100001160162&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE - server replied: ERROR url: https://fototeca-connector.icgc.cat/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=433987.6893147789524,4599402.361215376295,437186.4004343083943,4601011.033409469761&CRS=EPSG:25831&WIDTH=1030&HEIGHT=518&LAYERS=fotos&STYLES=2011100001160162&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE]`

**Comment by icgcaadell** [comment]
Hola
Ho sento, estem tenint problemes amb el servidor que dóna accés als fotogrames, en breu esperem tenir-ho operatiu, en principi no és un problema de la versió 1.1.5 però ara ho estem comprovant.
Gràcies!

**Comment by Isaac0H0E** [comment]
Genial, gràcies!

**Comment by icgcaadell** [comment]
Torna a funcionar la visualització de fotogrames, estan restaurant encara les descàrregues...

**Comment by Isaac0H0E** [comment]
Excel·lent! Gràcies pel feedback!

**Comment by icgcaadell** [comment]
Ja tornen a estar operatives les descàrregues de fotogrames. Disculpeu les molèsties
