### ISSUE TITLE
No es pot descarregar mdt i altres

### ISSUE THREAD

**Issue by RamondCC** [OpenICGC/QgisPlugin#8]
Cada cop que intento descarregar mdt o altres capes em diu que "l'àrea seleccionada és fora de Catalunya". 

Tinc el projecte amb 25831 i el piramidal topogràfic obert de fons. Versió Connector 1.1.9 i versió qgis 3.22.10-Białowieża

**Comment by icgcaadell** [comment]
Hola, gràcies per reportar el problema. Ets el segon usuari que li passa el mateix i no aconseguim reproduir-ho en les nostres màquines. 

Treballes amb windows o linux?

A la versió v1.1.9 hem afegit un petit sistema de registre d'events per intentar obtenir més informació d'aquests problemes. Podries activar-ho i informar-nos del que et diu?. Per activar-ho cal anar al menú "**Ajuda / Activar registre d'informació de debug**" això farà que si mostres les finestres de missatges de QGIS (Botó a la part inferior dreta de QGIS) et surti una subfinestra d'OpenICGC on anirà mostrant events que s'executen.
![image](https://user-images.githubusercontent.com/47522822/190090246-1e329c85-1505-4059-baa5-3734a5f3aaf0.png)
![image](https://user-images.githubusercontent.com/47522822/190091174-b1fc7e9b-b293-4a11-8b28-0fb1a26c7e0c.png)
![image](https://user-images.githubusercontent.com/47522822/190091242-6a878ab8-acf8-4e2a-945e-d1acf23ce772.png)

Caldria activar el sistema i després intentar fer una descàrrega per registrar la informació del procés.

Gràcies i disculpa les molèsties

**Comment by RamondCC** [comment]
Bones.

He fet el que m'heu dit intentant descarregar una comarca o per àrea i  el
registre diu:

2022-09-14T11:17:38     INFO    Debug log disabled

2022-09-14T11:17:45     INFO    Debug log enabled:
C:\Users\rnoguer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\OpenICGC.log

2022-09-14T11:18:19     INFO    Download tool user selection (dt_counties)

2022-09-14T11:18:19     INFO    Use project EPSG for geometry: 25831

2022-09-14T11:18:19     INFO    Download geometry 510690.37656934408005327
4684467.98963007889688015, 510690.37656934408005327
4684467.98963007889688015 (EPSG:25831)

2022-09-14T11:18:19     INFO    Geometry (point) buffered 1

2022-09-14T11:18:19     INFO    Check Catalonia limits cat_limits

2022-09-14T11:18:19     WARNING    The selected area is outside Catalonia:
<QgsRectangle: 510689.37656934408005327 4684466.98963007889688015,
510691.37656934408005327 4684468.98963007889688015>

2022-09-14T11:18:37     INFO    Download tool user selection (dt_counties)

2022-09-14T11:18:37     INFO    Use project EPSG for geometry: 25831

2022-09-14T11:18:37     INFO    Download geometry 510532.34916870866436511
4684535.03155762143433094, 510532.34916870866436511
4684535.03155762143433094 (EPSG:25831)

2022-09-14T11:18:37     INFO    Geometry (point) buffered 1

2022-09-14T11:18:37     INFO    Check Catalonia limits cat_limits

2022-09-14T11:18:37     WARNING    The selected area is outside Catalonia:
<QgsRectangle: 510531.34916870866436511 4684534.03155762143433094,
510533.34916870866436511 4684536.03155762143433094>

2022-09-14T11:18:56     INFO    Download tool user selection (dt_area)

2022-09-14T11:18:56     INFO    Use project EPSG for geometry: 25831

2022-09-14T11:18:56     INFO    Download geometry 509984.04197559482418001
4684135.17434692289680243, 512009.66592919442337006
4684944.46618654020130634 (EPSG:25831)

2022-09-14T11:18:56     INFO    Check Catalonia limits 5k_limits

2022-09-14T11:18:56     WARNING    The selected area is outside Catalonia:
<QgsRectangle: 509984.04197559482418001 4684135.17434692289680243,
512009.66592919442337006 4684944.46618654020130634>


El missatges registrats diuen:

2022-09-14T11:18:18     INFO    Eina de descàrrega : Selecciona una comarca

2022-09-14T11:18:52     INFO    Eina de descàrrega : Selecciona una àrea


Espero que us ajudi...


Merci!




*Ramon Noguer Feixas*
Enginyer Tècnic Forestal
Num. Col. 4.867
Mob. 649798749


Missatge de icgcaadell ***@***.***> del dia dc., 14 de set.
2022 a les 9:40:

**Comment by icgcaadell** [comment]
Hola

No aconsegueixo veure el problema ...
Et sabria greu instal·lar-te la versió adjunta (zip) que mostra més informació a veure si detecto alguna cosa?
[OpenICGC-1.1.9.zip](https://github.com/OpenICGC/QgisPlugin/files/9566293/OpenICGC-1.1.9.zip)

Podries també intentar carregar els arxius geojson de la carpeta: %appdata%\QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\data que són els geojson que fem servir per validar els límits de Catalunya, a veure si se't visualitzen correctament sobre el topogràfic de Catalunya?

Gràcies!

**Comment by RamondCC** [comment]
Bon dia.
Les capes geojnson es veuen a lloc.

adjunto logs.

*avis de pyton:*

2022-09-15T10:53:42     WARNING
warning:C:\Users/rnoguer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\resources3\wms.py:154:
DeprecationWarning: invalid escape sequence \w
              reg_ex_filter="(\w+(\d{4})\w*)\s+"):

             traceback: File "", line 1, in
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\pyplugin_installer\installer.py",
line 275, in showPluginManagerWhenReady
              iface.pluginManagerInterface().showPluginManager(tabIndex)
              File "", line 1, in
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\pyplugin_installer\installer.py",
line 657, in installFromZipFile
              reloadPlugin(pluginName) # unloadPlugin + loadPlugin +
startPlugin
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 588,
in reloadPlugin
              started = startPlugin(packageName)
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 443,
in startPlugin
              if not _startPlugin(packageName):
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 423,
in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File
"C:\Users/rnoguer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\__init__.py",
line 29, in classFactory
              from .openicgc import OpenICGC
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888,
in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File
"C:\Users/rnoguer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\openicgc.py",
line 64, in
              from .resources3.wms import get_historic_ortho,
get_lastest_ortoxpres, get_superexpedita_ortho, get_full_ortho
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888,
in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 851, in exec_module
              File "", line 988, in get_code
              File "", line 918, in source_to_code
              File "", line 228, in _call_with_frames_removed


2022-09-15T10:53:42     WARNING
warning:C:\Users/rnoguer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\resources3\wms.py:176:
DeprecationWarning: invalid escape sequence \d
              reg_ex_filter="((\d{4})_.+_ortofoto_(rgb|irc))\s*",

             traceback: File "", line 1, in
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\pyplugin_installer\installer.py",
line 275, in showPluginManagerWhenReady
              iface.pluginManagerInterface().showPluginManager(tabIndex)
              File "", line 1, in
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\pyplugin_installer\installer.py",
line 657, in installFromZipFile
              reloadPlugin(pluginName) # unloadPlugin + loadPlugin +
startPlugin
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 588,
in reloadPlugin
              started = startPlugin(packageName)
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 443,
in startPlugin
              if not _startPlugin(packageName):
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 423,
in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File
"C:\Users/rnoguer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\__init__.py",
line 29, in classFactory
              from .openicgc import OpenICGC
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888,
in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File
"C:\Users/rnoguer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\openicgc.py",
line 64, in
              from .resources3.wms import get_historic_ortho,
get_lastest_ortoxpres, get_superexpedita_ortho, get_full_ortho
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888,
in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 851, in exec_module
              File "", line 988, in get_code
              File "", line 918, in source_to_code
              File "", line 228, in _call_with_frames_removed


2022-09-15T10:53:42     WARNING
warning:C:\Users/rnoguer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\resources3\wms.py:203:
DeprecationWarning: invalid escape sequence \w
              reg_ex_filter="(sen2(\w+)_(\d+))\s+"):

             traceback: File "", line 1, in
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\pyplugin_installer\installer.py",
line 275, in showPluginManagerWhenReady
              iface.pluginManagerInterface().showPluginManager(tabIndex)
              File "", line 1, in
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\pyplugin_installer\installer.py",
line 657, in installFromZipFile
              reloadPlugin(pluginName) # unloadPlugin + loadPlugin +
startPlugin
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 588,
in reloadPlugin
              started = startPlugin(packageName)
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 443,
in startPlugin
              if not _startPlugin(packageName):
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 423,
in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File
"C:\Users/rnoguer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\__init__.py",
line 29, in classFactory
              from .openicgc import OpenICGC
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888,
in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File
"C:\Users/rnoguer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\openicgc.py",
line 64, in
              from .resources3.wms import get_historic_ortho,
get_lastest_ortoxpres, get_superexpedita_ortho, get_full_ortho
              File
"C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888,
in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 851, in exec_module
              File "", line 988, in get_code
              File "", line 918, in source_to_code
              File "", line 228, in _call_with_frames_removed



*OGR:*

2022-09-15T10:53:42     WARNING    Cannot open {
             "type": "FeatureCollection",
             "name": "simple",
             "crs": { "type": "name", "properties": { "name":
"urn:ogc:def:crs:EPSG::25831" } },
             "features": [
             { "type": "Feature", "properties": { "id": 0 }, "geometry": {
"type": "Polygon", "coordinates": [ [ [ 304457.290340574458241,
4758033.341267678886652 ], [ 300160.834704967564903,
4683919.481553458608687 ], [ 283512.069116991071496,
4639880.811288491822779 ], [ 266863.303529014694504,
4608731.507930342108011 ], [ 251825.708804390684236,
4504542.458766875788569 ], [ 295327.322114910115488,
4476078.440180979669094 ], [ 339903.049334330891725,
4505079.515721328556538 ], [ 322717.226791903492995,
4527635.907808261923492 ], [ 445166.212406698206905,
4567378.122437627054751 ], [ 452147.952814559219405,
4582952.774116697721183 ], [ 527335.926437678863294,
4628065.558290572836995 ], [ 534317.666845540050417,
4704864.702777042984962 ], [ 469333.775356986618135,
4713994.671002711169422 ], [ 443555.041543345665559,
4707012.930594847537577 ], [ 388238.175234907655977,
4722050.525319471955299 ], [ 368367.067920226138085,
4741384.575679702684283 ], [ 304457.290340574458241,
4758033.341267678886652 ] ] ] } }
             ]
             }
              (Failed to read GeoJSON data).(Failed to read GeoJSON data)

2022-09-15T10:53:42     WARNING    Cannot open
{"type":"FeatureCollection","name":"divisions-administratives-v2r0-catalunya-1000000-20210701","crs":{"type":"name","properties":{"name":"EPSG:25831"}},"features":[{"type":"Feature","geometry":{"type":"MultiPolygon","coordinates":[[[[300644.45,4494148.85],[300646.24,4494149.65],[300647.24,4494150.62],[300648.54,4494152.97],[300649.07,4494155.43],[300649.08,4494157.08],[300648.79,4494159.26],[300648.11,4494162.05],[300646.88,4494166.17],[300645.19,4494170.21],[300643.57,4494172.76],[300641.63,4494174.98],[300639.46,4494176.84],[300613.63,4494196.25],[300608.13,4494199.93],[300602.21,4494203.03],[300598.84,449420.....

....

282869.997980243409984, 4490979.996050633490086 ], [
282870.001439255196601, 4488570.001779474318027 ], [
286399.995912368409336, 4488570.002100352197886 ], [
286400.000835966260638, 4488470.00472635962069 ], [ 289929.999966211675201,
4488469.994999750517309 ], [ 289930.001354870502837,
4488370.000910380855203 ], [ 293630.002475327230059,
4488370.002074592746794 ], [ 293629.999921411275864,
4490580.002789653837681 ] ] ] } }
             ]
             }
              (Failed to read GeoJSON data).(Failed to read GeoJSON data)

2022-09-15T10:53:42     WARNING    Cannot open {
             "type": "FeatureCollection",
             "name": "25k",
             "crs": { "type": "name", "properties": { "name":
"urn:ogc:def:crs:EPSG::25831" } },
             "features": [
             { "type": "Feature", "properties": { "gid": 0 }, "geometry": {
"type": "MultiPolygon", "coordinates": [ [ [ [ 329240.0, 4503660.0 ], [
329240.0, 4494410.0 ], [ 314920.0, 4494410.0 ], [ 314920.0, 4485500.0 ], [
300460.0, 4485500.0 ], [ 300460.0, 4485860.0 ], [ 286330.0, 4485860.0 ], [
286330.0, 4486250.0 ], [ 272210.0, 4486250.0 ], [ 272210.0, 4495920.0 ], [
258380.0, 4495920.0 ], [ 258380.0, 4505730.0 ], [ 258680.0, 4505730.0 ], [
258680.0, 4514980.0 ], [ 258990.0, 4514980.0 ], [ 258990.0, 4524230.0 ], [
259290.....

*  ...*

  (Failed to read GeoJSON data).(Failed to read GeoJSON data)


*Missatges:*

2022-09-15T10:53:46     INFO    El connector s'ha instal·lat correctament

2022-09-15T10:54:44     INFO    Eina de descàrrega : Selecciona una àrea


*OPEN ICGC*

2022-09-15T10:54:08     INFO    Debug log enabled:
C:\Users\rnoguer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\OpenICGC.log

2022-09-15T10:54:08     INFO    OS: Windows (win32)

2022-09-15T10:54:08     INFO    QGIS version: 3.22.10-Białowieża

2022-09-15T10:54:08     INFO    Python version: 3.9.5 (tags/v3.9.5:0a7dcbd,
May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

2022-09-15T10:54:08     INFO    OpenICGC version: 1.1.9

2022-09-15T10:54:45     INFO    Download tool user selection (dt_area)

2022-09-15T10:54:45     INFO    Use project EPSG for geometry: 25831

2022-09-15T10:54:45     INFO    Download geometry 444499.05307771579828113
4653941.28875241987407207, 471248.36883841181406751
4669686.13916852604597807 (EPSG:25831)

2022-09-15T10:54:45     INFO    Check Catalonia limits 5k_limits:
(<QgsGeometry: null>, '')

2022-09-15T10:54:45     WARNING    The selected area is outside Catalonia:
<QgsRectangle: 444499.05307771579828113 4653941.28875241987407207,
471248.36883841181406751 4669686.13916852604597807>


Espero que ajudi...


Ja em dirás


Merci!



*Ramon Noguer Feixas*
Enginyer Tècnic Forestal
Num. Col. 4.867
Mob. 649798749


Missatge de Ramon Noguer ***@***.***> del dia dc., 14 de set.
2022 a les 14:48:

**Comment by icgcaadell** [comment]
Bon dia,

Moltes gràcies per la informació. He vist que el problema està en la càrrega interna dels geojson de limits de Catalunya que per alguna raó no es carreguen correctament en el teu equip.

_**2022-09-15T10:54:45     INFO    Check Catalonia limits 5k_limits: (<QgsGeometry: null>, '')**_

T'adjunto una versió del plugin modificada que hauria d'evitar el problema (si no carrega els límits no els comprova i segueix ...), que mostra més logs i ve amb la opció de log activada per defecte. Podries tornar a enviar-nos la informació que et mostra la nova versió? (amb la pestanya OpenICGC hi ha prou)

Salutacions
[OpenICGC-1.1.9.zip](https://github.com/OpenICGC/QgisPlugin/files/9581349/OpenICGC-1.1.9.zip)

**Comment by RamondCC** [comment]
Boon dia!

Funciona!

Però mirant el registre veig un avís de "  Catalonia limits 5k_limits are
empty" ... et copio el registre per si creus que pugui ser important..:

2022-09-16T08:50:56     INFO    Debug log enabled:
C:\Users\rnoguer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\OpenICGC.log

2022-09-16T08:50:56     INFO    OS: Windows (win32)

2022-09-16T08:50:56     INFO    QGIS version: 3.22.10-Białowieża

2022-09-16T08:50:56     INFO    Python version: 3.9.5 (tags/v3.9.5:0a7dcbd,
May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

2022-09-16T08:50:56     INFO    OpenICGC version: 1.1.9

2022-09-16T08:50:56     INFO    Initializing OpenICGC

2022-09-16T08:50:56     INFO    Load geometry limits:
C:\Users\rnoguer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\data\cat_rect_limits.geojson
(buffer: 0, segments: 10, EPSG:EPSG:25831)

2022-09-16T08:50:56     INFO    Load geometry limits:
C:\Users\rnoguer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\data\cat_simple_limits.geojson
(buffer: 0, segments: 10, EPSG:EPSG:25831)

2022-09-16T08:50:56     INFO    Load geometry limits:
C:\Users\rnoguer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\data\cat_limits.geojson
(buffer: 250, segments: 10, EPSG:EPSG:25831)

2022-09-16T08:50:56     INFO    Load geometry limits:
C:\Users\rnoguer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\data\cat_tall5k_limits.geojson
(buffer: 0, segments: 10, EPSG:EPSG:25831)

2022-09-16T08:50:56     INFO    Load geometry limits:
C:\Users\rnoguer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\data\cat_tall25k_limits.geojson
(buffer: 0, segments: 10, EPSG:EPSG:25831)

2022-09-16T08:50:56     INFO    Initializing GUI

2022-09-16T08:50:57     INFO    HTTP resources files find URL:
https://datacloud.icgc.cat/datacloud/topografia-territorial/tif_unzip
pattern: (topografia-territorial-v\d+r\d+-(\d+)\.tif) found: 3

2022-09-16T08:50:57     INFO    HTTP resources files find URL:
https://datacloud.icgc.cat/datacloud/divisions-administratives/json_unzip
pattern:
(divisions-administratives-v\d+r\d+\-(\D+)(?:-(\d+))*-(\d{8})\.json) found:
31

2022-09-16T08:50:57     INFO    HTTP resources files find URL:
https://datacloud.icgc.cat/datacloud/talls_ETRS89/json_unzip pattern:
(tall(\w+)etrs\w+\.json) found: 8

2022-09-16T08:50:57     INFO    HTTP resources files find URL:
https://datacloud.icgc.cat/datacloud/met2_ETRS89/mosaic pattern:
(met\w+\.\w+) found: 1

2022-09-16T08:50:57     INFO    HTTP resources files find URL:
https://datacloud.icgc.cat/datacloud/met5_ETRS89/mosaic pattern:
(met\w+\.\w+) found: 1

2022-09-16T08:50:57     INFO    HTTP resources files find URL:
https://datacloud.icgc.cat/datacloud/ndvi/tif pattern:
(ndvi-v\d+r\d+-(\d+)\.tif) found: 5

2022-09-16T08:50:57     INFO    WMS resources info URL:
http://geoserveis.icgc.cat/servei/catalunya/orto-territorial/wms pattern:
<Name>(.+)</Name>\s+<Title>(.+)</Title> found: 114

2022-09-16T08:50:58     INFO    HTTP resources files find URL:
https://datacloud.icgc.cat/datacloud/orto-territorial/gpkg_unzip pattern:
(ortofoto-(\w+)-(\d+)(c*m)-(\w+)-(\d{4})\.gpkg) found: 67

2022-09-16T08:50:58     INFO    FME resources URL:
https://descarregues.icgc.cat found: 42

2022-09-16T08:50:58     INFO    Initialization complete

2022-09-16T08:52:00     INFO    Download tool user selection (dt_area)

2022-09-16T08:52:00     INFO    Use project EPSG for geometry: 25831

2022-09-16T08:52:00     INFO    Download geometry 491278.44667737709823996
4687239.96430769097059965, 492735.67861167521914467
4688153.42090367432683706 (EPSG:25831)

2022-09-16T08:52:00     WARNING    Catalonia limits 5k_limits are empty
<QgsGeometry: null> (EPSG: EPSG:25831)

2022-09-16T08:52:09     INFO    Download filename: met2_20220916_085209.tif

2022-09-16T08:52:09     INFO    Download URL:
***@***.***/fmedatastreaming/Descarrega_basica/geotiff2format_clip_coor.fmw?SW_X=491278.45&SW_Y=4687239.96&NE_X=492735.68&NE_Y=4688153.42&poligon=&DEF_NAME=met2&Format=GEOTIFF&Projecte=met2&Codi=&piramide=True&referrer=OpenICGC_v1.1.9


Merci!



*Ramon Noguer Feixas*
Enginyer Tècnic Forestal
Num. Col. 4.867
Mob. 649798749


Missatge de icgcaadell ***@***.***> del dia dv., 16 de set.
2022 a les 8:39:

**Comment by icgcaadell** [comment]
Hola

Ha funcionat.. però faig trampes, m'he saltat el control en aquest cas :)

És molt extrany, sembla que carrega:
**_2022-09-16T08:50:56     INFO    Load geometry limits:
C:\Users\rnoguer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\data\cat_tall5k_limits.geojson
(buffer: 0, segments: 10, EPSG:EPSG:25831)_**

Però després està buit:
**_2022-09-16T08:52:00     WARNING    Catalonia limits 5k_limits are empty
<QgsGeometry: null> (EPSG: EPSG:25831)_**

i en teoria he afegit un control a la càrrega perquè mostri un warning si no va bé la càrrega ...

Podries executar en la consola python de QGIS aquestes comandes?

```
import os
pathname = os.path.join(os.environ["appdata"], 
r"QGIS\QGIS3\profiles\default\python\plugins\OpenICGC\data\cat_tall5k_limits.geojson")
os.path.exists(pathname)
QgsVectorLayer(pathname, "prova", "ogr").getFeature(0).geometry()
```

És el codi que faig servir per la càrrega. Hauria de retornar un True (arxiu trobat) i mostrar una geometria amb punts (la del geojson)

Gràcies per l'ajuda

**Comment by RamondCC** [comment]
Dma ho provo que ja he sortit de l'oficina

El dc., 14 de set. 2022, 14:36, icgcaadell ***@***.***> va
escriure:

**Comment by RamondCC** [comment]
em diu això...

[image: image.png]


*Ramon Noguer Feixas*
Enginyer Tècnic Forestal
Num. Col. 4.867
Mob. 649798749


Missatge de icgcaadell ***@***.***> del dia dv., 16 de set.
2022 a les 9:20:

**Comment by icgcaadell** [comment]
Disculpa, no puc veure la imatge

**Comment by icgcaadell** [comment]
Tanco el tema per inactivitat. Entenc que s'ha solucionat el problema

**Comment by RamondCC** [comment]
Si. Merci.

Perdò que no havia dit res.

El dl., 14 de nov. 2022, 12:35, icgcaadell ***@***.***> va
escriure:
