### ISSUE TITLE
WinError 10060

### ISSUE THREAD

**Issue by GCmartini** [OpenICGC/QgisPlugin#9]
Buenas, intente de mil manera solucionar el error "WinError 10060" pero no hubo forma. Tengo compañeros de trabajo que estan en otras locaciones con diferentes conexiones a internet y  nos sucede a todos los mismo. Les dejo un print de pantalla y el log a ver si me ayudar a resolver.

![image](https://user-images.githubusercontent.com/114230784/191951393-70b89491-4593-4e78-9411-ab7d41254d8c.png)

[OpenICGC.log](https://github.com/OpenICGC/QgisPlugin/files/9633188/OpenICGC.log)

Desde ya muchas gracias, saludos!

**Comment by icgcaadell** [comment]
Hola, gracias por reportar el problema.

Parece que hay algún tipo de problema de conexión con alguno de los dos servicios web que usamos para buscar la ubicación de un lugar. Acabo de probar las búsquedas en dos equipos diferentes y nos ha funcionado.

¿Hoy siguen sin funcionar las búsquedas? (¿podría ser un problema puntual?)

En caso contrario, ¿podríais intentar acceder con el navegador directamente a los servicios web? (ICGC y Catastro)
https://eines.icgc.cat/geocodificador/soap/ws/wss_1.0?wsdl
http://ovc.catastro.meh.es/ovcservweb/OVCSWLocalizacionRC/OVCCoordenadas.asmx?wsdl

Si tampoco os funciona, ¿Podríais intentar hacer un TraceRoute desde una consola?
**_tracert eines.icgc.cat_**

A ver si podemos encontrar el problema...

Saludos

**Comment by GCmartini** [comment]
Hola, gracias a ti por responder! Lamentablemente seguimos con el mismo inconveniente, la solución que encontramos fue volver a la versión 1.1.8 la cual no nos da ningún error.
Solemos trabajar con una VPN en Windows que apuna contra los servidores PostGIS, pero conectado o no a la VPN la versión 1.1.9 nos arroja el mismo error. Tenemos personal en distintas locaciones y a todos nos sucede lo mismo.  Te dejo los resultados de las pruebas, desde el navegados accedo con y sin VPN. Luego realice dos TraceRoute, el primero con VPN el segundo directo.

**Prueba con navegador:**
![image](https://user-images.githubusercontent.com/114230784/193052338-6a3368f2-b1f9-4354-9d50-c1daa3208fdc.png)
![image](https://user-images.githubusercontent.com/114230784/193052351-113ae1a2-19d7-4923-a6bf-e594089fad2e.png)

**TraceRoute:**
Traza a la dirección eines.icgc.cat [84.88.72.33]
sobre un máximo de 30 saltos:

  1    26 ms    26 ms    26 ms  192.168.10.1
  2    72 ms    26 ms    36 ms  172.21.1.209
  3    26 ms    26 ms    26 ms  172.21.0.121
  4    30 ms    29 ms    29 ms  10.253.26.193
  5    28 ms    27 ms    27 ms  anella01.01.catnix.net [193.242.98.38]
  6     *        *        *     Tiempo de espera agotado para esta solicitud.
  7    29 ms    28 ms    28 ms  84.88.72.252
  8    32 ms    29 ms    30 ms  84.88.72.11
  9    29 ms    32 ms    29 ms  84.88.72.33

Traza completa.

C:\Users\amart>tracert eines.icgc.cat

Traza a la dirección eines.icgc.cat [84.88.72.33]
sobre un máximo de 30 saltos:

  1    <1 ms    <1 ms    <1 ms  xeneize1150 [192.168.1.1]
  2     5 ms     5 ms     6 ms  10.0.0.1
  3     6 ms     5 ms     5 ms  172.16.24.1
  4     6 ms     6 ms     6 ms  10.220.96.119
  5    39 ms    14 ms     7 ms  81.196.118.212
  6    27 ms    27 ms    27 ms  10.220.167.74
  7    36 ms    35 ms    35 ms  fra-ix.geant.net [80.81.192.173]
  8     *        *        *     Tiempo de espera agotado para esta solicitud.
  9     *        *        *     Tiempo de espera agotado para esta solicitud.
 10    66 ms    64 ms    64 ms  ae5.mx1.mad.es.geant.net [62.40.98.226]
 11    64 ms    64 ms    64 ms  rediris-ias-rediris.mad.es.geant.net [83.97.90.21]
 12    85 ms    85 ms    85 ms  anella-router.red.rediris.es [130.206.214.98]
 13     *        *        *     Tiempo de espera agotado para esta solicitud.
 14    86 ms    86 ms    86 ms  84.88.72.252
 15    75 ms    75 ms    74 ms  84.88.72.11
 16    74 ms    74 ms    74 ms  84.88.72.33

Traza completa.

**Comment by icgcaadell** [comment]
Hola

Os conecta perfectamente con los servidores, o sea que creo que podemos descartar problemas de conexión o VPN.

He revisado el código y en la última versión del plugin 1.1.9 actualizamos la librería de terceros suds (que facilita las consultas vía WebService) de la versión v1.3 a v1.4. Aunque a nosotros nos funciona en nuestros equipos, mirando el traceback creo que  podría ser éste el problema...

Os he generado una versión del plugin 1.1.9 con la versión anterior de suds v1.3 y con la opción de mostrar más logs activada por defecto:
[OpenICGC-1.1.9b.zip](https://github.com/OpenICGC/QgisPlugin/files/9681341/OpenICGC-1.1.9b.zip)
¿Podrías instalarla manualmente vía archivo zip i probar si os funcionan las búsquedas?

También debería crear una subventana de mensajes de OpenICGC donde se va mostrando información de los procesos...
![image](https://user-images.githubusercontent.com/47522822/193205666-8d504e9d-722b-45b8-bf51-88a928f0f1b5.png)

Saludos

**Comment by icgcaadell** [comment]
Cierro el tema por inactividad. Entiendo que se ha solucionado el problema
